#!/usr/bin/env python
import pycurl
import StringIO
import json
import hashlib
import uuid
import random
import string
import sys
import os
import subprocess

_useragent = "Mozilla/5.0 (Windows NT 6.1; rv:2.0.1) Gecko/20100101 Firefox/4.0.1"
_token = None

h = {}
h["client"] = "htmlshark"
h["clientRevision"] = "20100831"
h["Country"] = {}
h["Country"]["CC1"] = "0"
h["Country"]["CC2"] = "0"
h["Country"]["CC3"] = "0"
h["Country"]["CC4"] = "0"
h["Country"]["ID"] = "1"
h["privacy"] = 0
h["session"] = None
h["uuid"] = str(uuid.uuid4())

def prepToken(method):
    rnd = (''.join(random.choice(string.hexdigits) for x in range(6))).lower()
    return rnd + hashlib.sha1(method + ":" + _token + ":quitStealinMahShit:" + rnd).hexdigest()

def getToken():
    global h, _token
    p = {}
    p["parameters"] = {}
    p["parameters"]["secretKey"] = hashlib.md5(h["session"]).hexdigest()
    p["method"] = "getCommunicationToken"
    p["header"] = h
    o = StringIO.StringIO()
    c = pycurl.Curl()
    c.setopt(pycurl.POST, 1)
    c.setopt(pycurl.URL, "https://retrocowbell.grooveshark.com/service.php")
    c.setopt(pycurl.USERAGENT, _useragent)
    c.setopt(pycurl.WRITEFUNCTION, o.write)
    c.setopt(pycurl.POSTFIELDS, json.JSONEncoder().encode(p))
    c.setopt(pycurl.HTTPHEADER, ["Content-Type:"])
    c.setopt(pycurl.COOKIE, "PHPSESSID=" + h["session"])
    c.perform()
    result = json.JSONDecoder().decode(o.getvalue())
    _token = result["result"]

def getSearchResultsEx(query):
    p = {}
    p["parameters"] = {}
    p["parameters"]["limit"] = 25
    p["parameters"]["offset"] = 1
    p["parameters"]["type"] = "Songs"
    p["parameters"]["query"] = query
    p["method"] = "getSearchResultsEx"
    p["header"] = h
    p["header"]["token"] = prepToken("getSearchResultsEx")
    o = StringIO.StringIO()
    c = pycurl.Curl()
    c.setopt(pycurl.POST, 1)
    c.setopt(pycurl.URL, "http://listen.grooveshark.com/more.php?" + p["method"])
    c.setopt(pycurl.USERAGENT, _useragent)
    c.setopt(pycurl.WRITEFUNCTION, o.write)
    c.setopt(pycurl.POSTFIELDS, json.JSONEncoder().encode(p))
    c.setopt(pycurl.REFERER, "http://retro.grooveshark.com/main.swf?cowbell=5c23503bcefdad39a8835559bb91740c")
    c.setopt(pycurl.HTTPHEADER, ["Content-Type:"])
    c.setopt(pycurl.COOKIE, "PHPSESSID=" + h["session"])
    c.perform()
    result = json.JSONDecoder().decode(o.getvalue())
    result = result["result"]["result"]
    return result

def getStreamKeyFromSongIDEx(id):
    p = {}
    p["parameters"] = {}
    p["parameters"]["mobile"] = "false"
    p["parameters"]["prefetch"] = "false"
    p["parameters"]["songID"] = id
    p["parameters"]["country"] = h["Country"]
    p["header"] = h
    p["header"]["client"] = "jsqueue"
    p["header"]["clientRevision"] = "20101012.37"
    p["header"]["token"] = prepToken("getStreamKeyFromSongIDEx")
    p["method"] = "getStreamKeyFromSongIDEx"
    o = StringIO.StringIO()
    c = pycurl.Curl()
    c.setopt(pycurl.POST, 1)
    c.setopt(pycurl.URL, "http://listen.grooveshark.com/more.php?" + p["method"])
    c.setopt(pycurl.USERAGENT, _useragent)
    c.setopt(pycurl.WRITEFUNCTION, o.write)
    c.setopt(pycurl.POSTFIELDS, json.JSONEncoder().encode(p))
    c.setopt(pycurl.REFERER, "http://retro.grooveshark.com/main.swf?cowbell=5c23503bcefdad39a8835559bb91740c")
    c.setopt(pycurl.HTTPHEADER, ["Content-Type:"])
    c.setopt(pycurl.COOKIE, "PHPSESSID=" + h["session"])
    c.perform()
    result = json.JSONDecoder().decode(o.getvalue())
    return result

def header_cb(buf):
    global h
    if "PHPSESSID" in buf:
        buf = buf.split(' ')
        h["session"] = buf[1][10:-1]

def init():
    o = StringIO.StringIO()
    c = pycurl.Curl()
    c.setopt(pycurl.URL, "http://listen.grooveshark.com/")
    c.setopt(pycurl.USERAGENT, _useragent)
    c.setopt(pycurl.WRITEFUNCTION, o.write)
    c.setopt(pycurl.HEADERFUNCTION, header_cb)
    c.perform()
    print "Initialized."
if len(sys.argv) < 2:
    print "Query Required"
    exit()
init()
getToken()
m = 0
s = getSearchResultsEx(sys.argv[1])
for l in s:
    m += 1
    print str(m) + ': "' + l["SongName"] + '" by "' + l["ArtistName"] + '" (' + l["AlbumName"] + ')'
    if m == 10: break
id = input("Enter the Song ID you wish to download or (q) to exit:")
if id == None: exit()
stream = getStreamKeyFromSongIDEx(s[id]["SongID"])
#print 'wget --post-data=streamKey=%s -O "%s - %s.mp3" "http://%s/stream.php"' % {stream["result"]["streamKey"], s[id]["ArtistName"], s[id]["SongName"], stream["result"]["ip"]}
s =  'wget --post-data=streamKey=%s -O "%s - %s.mp3" "http://%s/stream.php"' % (stream["result"]["streamKey"], s[id]["ArtistName"], s[id]["SongName"], stream["result"]["ip"])
print s
p = subprocess.Popen(s, shell=True)
p.wait()
