#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Sun Jan 16 15:51:35 2011

import wx
import  wx.lib.newevent
import groove
import threading

# begin wxGlade: extracode
# end wxGlade

evtStatusUpdate, EVT_STATUS_UPDATE = wx.lib.newevent.NewEvent()
evtEnable, EVT_ENABLE = wx.lib.newevent.NewEvent()
evtAddResult, EVT_ADD_RESULT = wx.lib.newevent.NewEvent()
evtClearResults, EVT_CLEAR_RESULTS = wx.lib.newevent.NewEvent()

class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: wxFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.cb_type = wx.ComboBox(self, -1, choices=["Songs", "Artists", "Albums"], style=wx.CB_DROPDOWN|wx.CB_READONLY)
        self.txt_query = wx.TextCtrl(self, 1, "", style=wx.TE_PROCESS_ENTER)
        self.lst_results = wx.ListCtrl(self, -1, style=wx.LC_REPORT|wx.SUNKEN_BORDER)
        self.frame_statusbar = self.CreateStatusBar(1, 0)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade
        self.Bind(EVT_STATUS_UPDATE, self._StatusUpdate)
        self.Bind(EVT_ENABLE, self._Enable)
        self.Bind(EVT_ADD_RESULT, self._AddResult)
        self.Bind(EVT_CLEAR_RESULTS, self._ClearResults)
        self.Bind(wx.EVT_TEXT_ENTER, self._TextEnter, self.txt_query)

    def __set_properties(self):
        # begin wxGlade: wxFrame.__set_properties
        self.SetTitle("JTR's Grooveshark Downloader")
        self.SetSize((600, 400))
        self.cb_type.SetMinSize((100, 23))
        self.cb_type.SetSelection(0)
        self.frame_statusbar.SetStatusWidths([-1])
        # statusbar fields
        frame_statusbar_fields = [""]
        for i in range(len(frame_statusbar_fields)):
            self.frame_statusbar.SetStatusText(frame_statusbar_fields[i], i)
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: wxFrame.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_2.Add(self.cb_type, 0, wx.EXPAND, 0)
        sizer_2.Add(self.txt_query, 2, 0, 0)
        sizer_1.Add(sizer_2, 0, wx.EXPAND, 0)
        sizer_1.Add(self.lst_results, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        self.Layout()
        # end wxGlade

    def _StatusUpdate(self, event):
        self.frame_statusbar.SetStatusText(event.attr1)
    def _Enable(self, event):
        self.Enable(event.attr1)
    def _TextEnter(self, event):
        search_thread = t_search(self, event.GetString(), self.cb_type.GetValue())
        search_thread.start()
    def _AddResult(self, event):
        self.lst_results.InsertStringItem(self.lst_results.GetItemCount(), str(self.lst_results.GetItemCount()+1))
        self.lst_results.SetStringItem(self.lst_results.GetItemCount()-1, 1, event.attr1)
        self.lst_results.SetStringItem(self.lst_results.GetItemCount()-1, 2, event.attr2)
        self.lst_results.SetStringItem(self.lst_results.GetItemCount()-1, 3, event.attr3)
        self.lst_results.SetColumnWidth(1, wx.LIST_AUTOSIZE)
        self.lst_results.SetColumnWidth(2, wx.LIST_AUTOSIZE)
        self.lst_results.SetColumnWidth(3, wx.LIST_AUTOSIZE)
        self.lst_results.SetColumnWidth(4, wx.LIST_AUTOSIZE)
    def _ClearResults(self, event):
        if self.lst_results.GetItemCount() > 0: self.lst_results.DeleteAllItems()
# end of class wxFrame

class t_search(threading.Thread):
    def __init__ (self, _frame, _query, _type):
        threading.Thread.__init__(self)
        self.frame = _frame
        self.query = _query
        self.type = _type
    def run(self):
        wx.PostEvent(self.frame, evtEnable(attr1=False))
        wx.PostEvent(self.frame, evtStatusUpdate(attr1='Searching for \"' + self.query + '\"...'))
        results = groove.getSearchResultsEx(self.query, self.type)
        wx.PostEvent(self.frame, evtClearResults())
        for l in results:
            wx.PostEvent(self.frame, evtAddResult(attr1=l["SongName"], attr2=l["AlbumName"], attr3=l["ArtistName"]))
        wx.PostEvent(self.frame, evtStatusUpdate(attr1="Ready"))
        wx.PostEvent(self.frame, evtEnable(attr1=True))
class t_init(threading.Thread):
    def __init__ (self, _frame):
        threading.Thread.__init__(self)
        self.frame = _frame
    def run(self):
        wx.PostEvent(self.frame, evtStatusUpdate(attr1="Initializing..."))
        groove.init()
        wx.PostEvent(self.frame, evtStatusUpdate(attr1="Getting Token..."))
        groove.getToken()
        wx.PostEvent(self.frame, evtStatusUpdate(attr1="Ready"))
        wx.PostEvent(self.frame, evtEnable(attr1=True))

if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    frame = MyFrame(None, -1, "")
    frame.Disable()
    app.SetTopWindow(frame)

    frame.lst_results.InsertColumn(-1, "ID")
    frame.lst_results.InsertColumn(-1, "Title")
    frame.lst_results.InsertColumn(-1, "Album")
    frame.lst_results.InsertColumn(-1, "Artist")

    init_thread = t_init(frame)
    init_thread.start()
    frame.Show()
    app.MainLoop()
